/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as FinalRouteImport } from './routes/final'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RespondResultRouteImport } from './routes/respond.result'
import { Route as CategoriesCategoryIdLevelsRouteImport } from './routes/categories.$categoryId.levels'
import { Route as CategoriesCategoryIdLevelsLevelIdResultRouteImport } from './routes/categories.$categoryId.levels.$levelId.result'
import { Route as CategoriesCategoryIdLevelsLevelIdQuizRouteImport } from './routes/categories.$categoryId.levels.$levelId.quiz'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RespondResultRoute = RespondResultRouteImport.update({
  id: '/respond/result',
  path: '/respond/result',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdLevelsRoute =
  CategoriesCategoryIdLevelsRouteImport.update({
    id: '/$categoryId/levels',
    path: '/$categoryId/levels',
    getParentRoute: () => CategoriesRoute,
  } as any)
const CategoriesCategoryIdLevelsLevelIdResultRoute =
  CategoriesCategoryIdLevelsLevelIdResultRouteImport.update({
    id: '/$levelId/result',
    path: '/$levelId/result',
    getParentRoute: () => CategoriesCategoryIdLevelsRoute,
  } as any)
const CategoriesCategoryIdLevelsLevelIdQuizRoute =
  CategoriesCategoryIdLevelsLevelIdQuizRouteImport.update({
    id: '/$levelId/quiz',
    path: '/$levelId/quiz',
    getParentRoute: () => CategoriesCategoryIdLevelsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/final': typeof FinalRoute
  '/ranking': typeof RankingRoute
  '/respond/result': typeof RespondResultRoute
  '/categories/$categoryId/levels': typeof CategoriesCategoryIdLevelsRouteWithChildren
  '/categories/$categoryId/levels/$levelId/quiz': typeof CategoriesCategoryIdLevelsLevelIdQuizRoute
  '/categories/$categoryId/levels/$levelId/result': typeof CategoriesCategoryIdLevelsLevelIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/final': typeof FinalRoute
  '/ranking': typeof RankingRoute
  '/respond/result': typeof RespondResultRoute
  '/categories/$categoryId/levels': typeof CategoriesCategoryIdLevelsRouteWithChildren
  '/categories/$categoryId/levels/$levelId/quiz': typeof CategoriesCategoryIdLevelsLevelIdQuizRoute
  '/categories/$categoryId/levels/$levelId/result': typeof CategoriesCategoryIdLevelsLevelIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/final': typeof FinalRoute
  '/ranking': typeof RankingRoute
  '/respond/result': typeof RespondResultRoute
  '/categories/$categoryId/levels': typeof CategoriesCategoryIdLevelsRouteWithChildren
  '/categories/$categoryId/levels/$levelId/quiz': typeof CategoriesCategoryIdLevelsLevelIdQuizRoute
  '/categories/$categoryId/levels/$levelId/result': typeof CategoriesCategoryIdLevelsLevelIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/categories'
    | '/final'
    | '/ranking'
    | '/respond/result'
    | '/categories/$categoryId/levels'
    | '/categories/$categoryId/levels/$levelId/quiz'
    | '/categories/$categoryId/levels/$levelId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/categories'
    | '/final'
    | '/ranking'
    | '/respond/result'
    | '/categories/$categoryId/levels'
    | '/categories/$categoryId/levels/$levelId/quiz'
    | '/categories/$categoryId/levels/$levelId/result'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/categories'
    | '/final'
    | '/ranking'
    | '/respond/result'
    | '/categories/$categoryId/levels'
    | '/categories/$categoryId/levels/$levelId/quiz'
    | '/categories/$categoryId/levels/$levelId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  FinalRoute: typeof FinalRoute
  RankingRoute: typeof RankingRoute
  RespondResultRoute: typeof RespondResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respond/result': {
      id: '/respond/result'
      path: '/respond/result'
      fullPath: '/respond/result'
      preLoaderRoute: typeof RespondResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/levels': {
      id: '/categories/$categoryId/levels'
      path: '/$categoryId/levels'
      fullPath: '/categories/$categoryId/levels'
      preLoaderRoute: typeof CategoriesCategoryIdLevelsRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/categories/$categoryId/levels/$levelId/result': {
      id: '/categories/$categoryId/levels/$levelId/result'
      path: '/$levelId/result'
      fullPath: '/categories/$categoryId/levels/$levelId/result'
      preLoaderRoute: typeof CategoriesCategoryIdLevelsLevelIdResultRouteImport
      parentRoute: typeof CategoriesCategoryIdLevelsRoute
    }
    '/categories/$categoryId/levels/$levelId/quiz': {
      id: '/categories/$categoryId/levels/$levelId/quiz'
      path: '/$levelId/quiz'
      fullPath: '/categories/$categoryId/levels/$levelId/quiz'
      preLoaderRoute: typeof CategoriesCategoryIdLevelsLevelIdQuizRouteImport
      parentRoute: typeof CategoriesCategoryIdLevelsRoute
    }
  }
}

interface CategoriesCategoryIdLevelsRouteChildren {
  CategoriesCategoryIdLevelsLevelIdQuizRoute: typeof CategoriesCategoryIdLevelsLevelIdQuizRoute
  CategoriesCategoryIdLevelsLevelIdResultRoute: typeof CategoriesCategoryIdLevelsLevelIdResultRoute
}

const CategoriesCategoryIdLevelsRouteChildren: CategoriesCategoryIdLevelsRouteChildren =
  {
    CategoriesCategoryIdLevelsLevelIdQuizRoute:
      CategoriesCategoryIdLevelsLevelIdQuizRoute,
    CategoriesCategoryIdLevelsLevelIdResultRoute:
      CategoriesCategoryIdLevelsLevelIdResultRoute,
  }

const CategoriesCategoryIdLevelsRouteWithChildren =
  CategoriesCategoryIdLevelsRoute._addFileChildren(
    CategoriesCategoryIdLevelsRouteChildren,
  )

interface CategoriesRouteChildren {
  CategoriesCategoryIdLevelsRoute: typeof CategoriesCategoryIdLevelsRouteWithChildren
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoryIdLevelsRoute: CategoriesCategoryIdLevelsRouteWithChildren,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  FinalRoute: FinalRoute,
  RankingRoute: RankingRoute,
  RespondResultRoute: RespondResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
